[build]
  publish = "./"
  command = "echo 'Building with Netlify Includes'"

[build.environment]
  NETLIFY_BUILD_USE_INCLUDES = "true"
  
[functions.emails]
included_files = [
  "./emails/**"
]

[context]

  [context.production]

    [context.production.functions]

      [context.production.functions.emails]
      included_files = [
        "./emails/**"
      ]

  [context.main]

    [context.main.functions]

      [context.main.functions.emails]
      included_files = [
        "./emails/**"
      ]

# ========== REDIRECTS ==========

# Primary domain redirects
[[redirects]]
  from = "https://aldahub.netlify.app/*"
  to = "https://aldahub.com/:splat"
  status = 301
  force = true

# Blog pagination routes - QUAN TRỌNG: đặt TRƯỚC catch-all
[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/blog/"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/blog?page=:page"
  to = "/blog.html?page=:page"
  status = 200

# Blog category and tag routes - QUAN TRỌNG: đặt TRƯỚC catch-all
[[redirects]]
  from = "/blog/category/:category"
  to = "/blog.html?category=:category"
  status = 200

[[redirects]]
  from = "/blog/tag/:tag"
  to = "/blog.html?tag=:tag"
  status = 200

# Individual blog posts - QUAN TRỌNG: đặt TRƯỚC catch-all
[[redirects]]
  from = "/:slug"
  to = "/blog-post.html"
  status = 200

# Success page
[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

# Catch-all for SPA behavior - ĐẶT CUỐI CÙNG
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = { Method = ["GET"] }
